version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "src/PersonalWebApp"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "src/PersonalWebApp"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "src/PersonalWebApp/Blog"
    schedule:
      interval: "daily"
