version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/PersonalWebApp/src"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/PersonalWebApp/src"
    schedule:
      interval: "daily"
