name: PRs (cleanup)
on:
  pull_request_target:
    types: [ closed ]
    branches: [ "main" ]

permissions:
  id-token: write
  pull-requests: write

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    environment:
      name: pr
    steps:
    - name: OIDC Login via Azure CLI
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Delete PR Deployment Slot
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az webapp deployment slot delete --name app-ifesenko-centralus --resource-group ifesenko.com --slot pr-${{ github.event.number }}

    - name: Delete PR Comment With Webapp Url
      uses: thollander/actions-comment-pull-request@v3
      with:
        comment-tag: webapp-url
        mode: delete
