name: PRs
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

permissions:
  id-token: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.current-time.outputs.formattedTime }}.${{ github.run_number }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4.1.0
      with:
         dotnet-version: 9.x
        
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYYY.MM.DD
    
    - name: Build
      shell: pwsh
      run: .\build\build.ps1 --buildNumber=${{ steps.current-time.outputs.formattedTime }}.${{ github.run_number }}
    
    - name: Publish
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.current-time.outputs.formattedTime }}.${{ github.run_number }}
        path: ${{ github.workspace }}/build/artifacts/Build.StagingDirectory/*.zip

  deploy:
    name: Deploy PR
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pr
      url: ${{ steps.deploywebapp.outputs.webapp-url }}
    env:
      AZURE_WEBAPP_NAME: app-ifesenko-centralus
      AZURE_RESOURCE_GROUP: ifesenko.com
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.artifact-name }}
    
    - name: OIDC Login via Azure CLI
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Create New PR Deployment Slot
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az webapp deployment slot create --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --configuration-source staging --slot pr-${{ github.event.number }}
          az webapp config appsettings set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --settings AppSettings__CdnEndpoint='//${{ env.AZURE_WEBAPP_NAME }}-pr-${{ github.event.number }}.azurewebsites.net'
        
    - name: Deploy to PR Deployment Slot
      id: deploywebapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: pr-${{ github.event.number }}
        package: ${{ needs.build.outputs.artifact-name }}.zip
    
    - name: Comment PR With Webapp Url
      uses: thollander/actions-comment-pull-request@v3
      with:
        message: |
          ${{ steps.deploywebapp.outputs.webapp-url }}
        comment-tag: webapp-url